### ISSUE TITLE
[AVM Module Issue]:

### ISSUE THREAD

**Issue by pieter-jangoeman** [Azure/terraform-azurerm-avm-res-web-staticsite#70]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.4.0

### Description

There's a requirement about the azapi version: 

azapi (>= 0.1.0, < 1.14.0)

1.14.0 is limiting me to use some other AVM's, for example this one: 
Azure/avm-res-operationalinsights-workspace/azurerm

Most modules require you to have at lease some version, but don't limit you on having a too new version.

Please adjust so there's no conflicts when using up to date versions.

**Comment by donovm4** [comment]
Hello @pieter-jangoeman : 

Will take a look into this shortly 👍

**Comment by donovm4** [comment]
@pieter-jangoeman : 

Please see the latest release `v0.4.1` and let me know if these has been resolved.

**Comment by pieter-jangoeman** [comment]
Speaking about a quick fix, this seems to do the trick, thanks a lot
Donovan!

Kind regards,
Pieter-Jan

Op ma 4 nov 2024 om 18:06 schreef Donovan McCoy ***@***.***>:
